### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by axelsimon**
Added some information:
- introduce product acronyms early, as they are referenced later (DoT3k and DoTHAT)
- mention DoT3k no longer for sale
- add pictures to help people tell their product apart

### CODE REVIEW

**Comment by axelsimon** [comment]
This also leads me to a question. The README says:
> Display-o-Tron HAT (for A+, B+ and Pi 2)

However, the Display-o-Tron HAT product page says:
> Compatible with all 40-pin header Raspberry Pi models

Is this supposed to mean that the code in the `displayotron` repo is compatible only with DoTHATs on A+, B+ and Pi 2?

Or is it just an inconsistency that needs to be fixed, and the code is in fact also compatible with Pi0, Pi0W, Pi 3 and Pi 4?

**Comment by Gadgetoid** [comment]
First- thanks for making a PR for this. It's hard to overstate just how important these details are, and just how easy they are to overlook. It's really appreciated.

Second- yes the Display-o-Tron HAT and repository are compatible with all 40-pin Raspberry Pi models. I think this repository has just been left by the wayside since my attention has been elsewhere.

**Comment by axelsimon** [comment]
Hey @Gadgetoid, thanks for the quick answer and nice words!
I'll amend the text to reflect the information regarding compatibility with all 40-pin Raspberry Pis.

**Comment by Gadgetoid** [comment]
Brilliant stuff, thank you!

**Pull request merged**
